Slow geoserver connections
venicegeo/pz-access pull request #52
Opened 2018-04-13 17:49 UTC by akater320

PiazzaEnvironment now creates its own instance of RestTemplate and can set a non-default timeout.

2018-04-13 18:22 UTC, go0ty requested changes

2018-04-13 18:22 UTC, go0ty commented on src/test/java/access/test/PiazzaEnvironmentTests.java
> +//    @Test
Remove commented , unused code

2018-04-13 18:22 UTC, go0ty commented on src/test/java/access/test/PiazzaEnvironmentTests.java
> +                Mockito.endsWith("/workspaces/piazza.json"),
nice use of "endsWith"!

2018-04-13 18:22 UTC, go0ty commented on src/main/java/access/deploy/geoserver/PiazzaEnvironment.java
> +	private void createPostgresStore(RestTemplate restTemplate) {
What's the reasoning for passing the class-member variable via a method parameter? Do you want to do this vs. just using the member variable reference?

2018-04-13 18:30 UTC, akater320 commented on src/main/java/access/deploy/geoserver/PiazzaEnvironment.java
> +	private void createPostgresStore(RestTemplate restTemplate) {
Good catch. That was left over from when the RestTemplate was stack-scoped.
Should be fixed now.

2018-04-13 18:30 UTC, akater320 commented on src/test/java/access/test/PiazzaEnvironmentTests.java
> +//    @Test
Good call. Done.

2018-04-16 13:11 UTC, go0ty approved these changes

2018-04-16 13:12 UTC, merged